language: java
deploy:
  provider: releases
  api_key:
    secure: AApay8p7mDQhPthdEfgZrOuXLIHeMBZ1IYtSTy1scbHDBBarMHNmZOAX1cgr2kVhMay+rcx/CujogR9AnQ8r5c0clNzGR7Ypbpu2vaGJ9Q8aeDPaX6aq82Q69+nFrrfv7fbJAK87GjDV298efDE6M2d6ZqrFePrJgA40TJuyB6rwXl3UZqw7oiH3r1Zo8D1xLjsUcn82Gn/isH/FcG7c8hqF9oMOec9luRWdp0eNhxg662CgzSBIrC7CpugpKVd6pr1iFnmZQGfSdOxPH2mQt+wwzHStXTXEfrSrAz99F4P3IF3IARqRPNslZ84P2RSESCrzEcORtTuoL4jWQHd8w8o0IL5t+oo5eK7dVxsLnUJIEkwiDKeXTs41FPf9jJzU6i7J+ANj49m53JI3DKxMxuCPY5qgMlSUNp97NxQvRWyf0NPS3XB5N2MlA6l0lV4e3oO9SR+F3bg+slRj46Q/ObUpHT4hzuSc5BIC3KzId1kz+l69YjsIX8z2NpkDzkqZrIFg5M+6fxJrrn2oR8dgQeC1c9A/utFATuNzXBbzLXQnER/TFQE3N9b9gXGKpqirI/0+gvM6JHzyBAg8kaZ4r40DFFSIyn4s0N+6QgX1ETB1+fmlxFS6rXAeuyVx2oNq5FX3fWbvAzmR2Ze+QnxkSNUwpJR6OwuZ0gWEY6gB52Q=
  file_glob: true
  file: "build/distributions/xld-apigee-plugin-*.xldp"
  skip_cleanup: true
  on:
    tags: true
    repo: xebialabs-community/xld-apigee-plugin
